#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KawaiiPhysics

#include "Basic.hpp"

#include "KawaiiPhysics_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class KawaiiPhysics.KawaiiPhysicsLimitsDataAsset
// 0x0030 (0x0060 - 0x0030)
class UKawaiiPhysicsLimitsDataAsset final : public UDataAsset
{
public:
	TArray<struct FSphericalLimit>                SphericalLimits;                                   // 0x0030(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FCapsuleLimit>                  CapsuleLimits;                                     // 0x0040(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FPlanarLimit>                   PlanarLimits;                                      // 0x0050(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KawaiiPhysicsLimitsDataAsset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KawaiiPhysicsLimitsDataAsset")
	}
	static class UKawaiiPhysicsLimitsDataAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKawaiiPhysicsLimitsDataAsset>();
	}
};
DUMPER7_ASSERTS_UKawaiiPhysicsLimitsDataAsset;

SDK_NAMESPACE_END
