#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LEquipmentComponentBP

#include "Basic.hpp"

#include "ProjectP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LEquipmentComponentBP.LEquipmentComponentBP_C
// 0x0000 (0x0260 - 0x0260)
class ULEquipmentComponentBP_C final : public ULEquipmentComponent
{
public:
	class ALWeapon* SpawnWeaponWithClass(TSubclassOf<class ALWeapon> HandleWeaponClass, TSubclassOf<class ALWeapon> BladeWeaponClass);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LEquipmentComponentBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LEquipmentComponentBP_C")
	}
	static class ULEquipmentComponentBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULEquipmentComponentBP_C>();
	}
};
DUMPER7_ASSERTS_ULEquipmentComponentBP_C;

SDK_NAMESPACE_END
