#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNPCCharacterBP

#include "Basic.hpp"

#include "LNPCCharacterBP_classes.hpp"
#include "LNPCCharacterBP_parameters.hpp"


SDK_NAMESPACE_START

// Function LNPCCharacterBP.LNPCCharacterBP_C.ExecuteUbergraph_LNPCCharacterBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::ExecuteUbergraph_LNPCCharacterBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "ExecuteUbergraph_LNPCCharacterBP");

	Params::LNPCCharacterBP_C_ExecuteUbergraph_LNPCCharacterBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.OnExplostionDead
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Cut                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALNPCCharacterBP_C::OnExplostionDead(bool Cut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "OnExplostionDead");

	Params::LNPCCharacterBP_C_OnExplostionDead Parms{};

	Parms.Cut = Cut;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.ReceivePostBeginPlay
// (Event, Public, BlueprintEvent)

void ALNPCCharacterBP_C::ReceivePostBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "ReceivePostBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.DeadCharacterBP
// (Event, Public, BlueprintEvent)

void ALNPCCharacterBP_C::DeadCharacterBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "DeadCharacterBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "ReceiveEndPlay");

	Params::LNPCCharacterBP_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALNPCCharacterBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "ReceiveTick");

	Params::LNPCCharacterBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.SetCombatStateBP
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bCombatState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALNPCCharacterBP_C::SetCombatStateBP(bool bCombatState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "SetCombatStateBP");

	Params::LNPCCharacterBP_C_SetCombatStateBP Parms{};

	Parms.bCombatState = bCombatState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ALNPCCharacterBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.Dead_Physics
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PhysicsOn                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   DeltaSec                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InterpValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   PhysicalValue                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             BoneName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::Dead_Physics(bool PhysicsOn, float DeltaSec, float InterpValue, float PhysicalValue, class FName BoneName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "Dead_Physics");

	Params::LNPCCharacterBP_C_Dead_Physics Parms{};

	Parms.PhysicsOn = PhysicsOn;
	Parms.DeltaSec = DeltaSec;
	Parms.InterpValue = InterpValue;
	Parms.PhysicalValue = PhysicalValue;
	Parms.BoneName = BoneName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.LNPC_EyeFlash
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMeshComponent*                   MeshComp                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    OFF                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             ParamName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    On_Random                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   ParamValueON_Default                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ParamValueON_RandomMax                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ParamValueOFF                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::LNPC_EyeFlash(class UMeshComponent* MeshComp, bool OFF, class FName ParamName, bool On_Random, float ParamValueON_Default, float ParamValueON_RandomMax, float ParamValueOFF)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "LNPC_EyeFlash");

	Params::LNPCCharacterBP_C_LNPC_EyeFlash Parms{};

	Parms.MeshComp = MeshComp;
	Parms.OFF = OFF;
	Parms.ParamName = ParamName;
	Parms.On_Random = On_Random;
	Parms.ParamValueON_Default = ParamValueON_Default;
	Parms.ParamValueON_RandomMax = ParamValueON_RandomMax;
	Parms.ParamValueOFF = ParamValueOFF;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.GetNpcBGM
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            BGMCodeName                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALNPCCharacterBP_C::GetNpcBGM(class FName* BGMCodeName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "GetNpcBGM");

	Params::LNPCCharacterBP_C_GetNpcBGM Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BGMCodeName != nullptr)
		*BGMCodeName = Parms.BGMCodeName;
}


// Function LNPCCharacterBP.LNPCCharacterBP_C.UpdateHeadTagPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALNPCCharacterBP_C::UpdateHeadTagPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LNPCCharacterBP_C", "UpdateHeadTagPosition");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
