#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ObjectManagementSystemDataBP

#include "Basic.hpp"

#include "ObjectManagementSystemDataBP_classes.hpp"
#include "ObjectManagementSystemDataBP_parameters.hpp"


SDK_NAMESPACE_START

// Function ObjectManagementSystemDataBP.ObjectManagementSystemDataBP_C.ExecuteUbergraph_ObjectManagementSystemDataBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AObjectManagementSystemDataBP_C::ExecuteUbergraph_ObjectManagementSystemDataBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ObjectManagementSystemDataBP_C", "ExecuteUbergraph_ObjectManagementSystemDataBP");

	Params::ObjectManagementSystemDataBP_C_ExecuteUbergraph_ObjectManagementSystemDataBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ObjectManagementSystemDataBP.ObjectManagementSystemDataBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AObjectManagementSystemDataBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ObjectManagementSystemDataBP_C", "ReceiveTick");

	Params::ObjectManagementSystemDataBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ObjectManagementSystemDataBP.ObjectManagementSystemDataBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AObjectManagementSystemDataBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ObjectManagementSystemDataBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
