#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIBP_Drag_TestWindow

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass UIBP_Drag_TestWindow.UIBP_Drag_TestWindow_C
// 0x0010 (0x0098 - 0x0088)
class UUIBP_Drag_TestWindow_C final : public UDragDropOperation
{
public:
	class UUserWidget*                            WidgetReference;                                   // 0x0088(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FVector2D                              DragOffset;                                        // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIBP_Drag_TestWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIBP_Drag_TestWindow_C")
	}
	static class UUIBP_Drag_TestWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIBP_Drag_TestWindow_C>();
	}
};
DUMPER7_ASSERTS_UUIBP_Drag_TestWindow_C;

SDK_NAMESPACE_END
