#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIBP_TextImage

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass UIBP_TextImage.UIBP_TextImage_C
// 0x0000 (0x0030 - 0x0030)
class UUIBP_TextImage_C final : public URichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIBP_TextImage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIBP_TextImage_C")
	}
	static class UUIBP_TextImage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIBP_TextImage_C>();
	}
};
DUMPER7_ASSERTS_UUIBP_TextImage_C;

SDK_NAMESPACE_END
