#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIBP_ListData_Default

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass UIBP_ListData_Default.UIBP_ListData_Default_C
// 0x0028 (0x0050 - 0x0028)
class UUIBP_ListData_Default_C final : public UObject
{
public:
	class FName                                   ID;                                                // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   Label;                                             // 0x0030(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          Enabled;                                           // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIBP_ListData_Default_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIBP_ListData_Default_C")
	}
	static class UUIBP_ListData_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIBP_ListData_Default_C>();
	}
};
DUMPER7_ASSERTS_UUIBP_ListData_Default_C;

SDK_NAMESPACE_END
