#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIST_GetItem

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct UIST_GetItem.UIST_GetItem
// 0x0010 (0x0010 - 0x0000)
struct FUIST_GetItem final
{
public:
	class ULItem*                                 LItem_2_8694F6F546074B849CAE4E897EA9FC9B;          // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Count_5_1181196F44D2F170FE9CBE904D8F9A4C;          // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInvenItem_7_715FB78749BC83257F1494A99885087B;    // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_FUIST_GetItem;

SDK_NAMESPACE_END
