#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIST_FirstCategoryInfo

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct UIST_FirstCategoryInfo.UIST_FirstCategoryInfo
// 0x0010 (0x0010 - 0x0000)
struct FUIST_FirstCategoryInfo final
{
public:
	class UTexture2D*                             Icon_5_24D354294B99302A9A0BE986F8C9C061;           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Label_19_A8DE9C464502D12AD0289A8D54A0EF56;         // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FUIST_FirstCategoryInfo;

SDK_NAMESPACE_END
