#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Stat_Diff

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UIW_Stat_Diff.UIW_Stat_Diff_C
// 0x0010 (0x0270 - 0x0260)
class UUIW_Stat_Diff_C final : public UUserWidget
{
public:
	class UImage*                                 Img_Arrow;                                         // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_Diff;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetValue(int32 Value, int32 Divisor, int32 Decimal);
	void SetText(const class FText& Text);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIW_Stat_Diff_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIW_Stat_Diff_C")
	}
	static class UUIW_Stat_Diff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIW_Stat_Diff_C>();
	}
};
DUMPER7_ASSERTS_UUIW_Stat_Diff_C;

SDK_NAMESPACE_END
