#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Popup_BG

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UIW_Popup_BG.UIW_Popup_BG_C.SetContentsSize
// 0x0008 (0x0008 - 0x0000)
struct UIW_Popup_BG_C_SetContentsSize final
{
public:
	struct FVector2D                              Size;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIW_Popup_BG_C_SetContentsSize;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
