#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_DPad_Durability

#include "Basic.hpp"

#include "UIW_DPad_Durability_classes.hpp"
#include "UIW_DPad_Durability_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_DPad_Durability.UIW_DPad_Durability_C.ExecuteUbergraph_UIW_DPad_Durability
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_DPad_Durability_C::ExecuteUbergraph_UIW_DPad_Durability(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "ExecuteUbergraph_UIW_DPad_Durability");

	Params::UIW_DPad_Durability_C_ExecuteUbergraph_UIW_DPad_Durability Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.WidgetAnimationEvt_Ani_Durability_Warning_Start_K2Node_WidgetAnimationEvent_2
// (BlueprintEvent)

void UUIW_DPad_Durability_C::WidgetAnimationEvt_Ani_Durability_Warning_Start_K2Node_WidgetAnimationEvent_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "WidgetAnimationEvt_Ani_Durability_Warning_Start_K2Node_WidgetAnimationEvent_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_DPad_Durability_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.CompleteTween
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             CategoryName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_DPad_Durability_C::CompleteTween(class FName CategoryName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "CompleteTween");

	Params::UIW_DPad_Durability_C_CompleteTween Parms{};

	Parms.CategoryName = CategoryName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_DPad_Durability_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetBroken
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetBroken()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetBroken");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetBreak
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetBreak()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetBreak");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetWarning
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetWarning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetWarning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetFine
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetFine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetFine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetFull
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetFull()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetFull");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.ResetAnim
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::ResetAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "ResetAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.Show Grind Effect
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::Show_Grind_Effect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "Show Grind Effect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_DPad_Durability.UIW_DPad_Durability_C.SetEmpty
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_DPad_Durability_C::SetEmpty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_DPad_Durability_C", "SetEmpty");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
