#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_QA_ListItem

#include "Basic.hpp"

#include "UIW_QA_ListItem_classes.hpp"
#include "UIW_QA_ListItem_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_QA_ListItem.UIW_QA_ListItem_C.ExecuteUbergraph_UIW_QA_ListItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_QA_ListItem_C::ExecuteUbergraph_UIW_QA_ListItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_QA_ListItem_C", "ExecuteUbergraph_UIW_QA_ListItem");

	Params::UIW_QA_ListItem_C_ExecuteUbergraph_UIW_QA_ListItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_QA_ListItem.UIW_QA_ListItem_C.BndEvt__UIW_QA_ListItem_Btn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUIW_QA_ListItem_C::BndEvt__UIW_QA_ListItem_Btn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_QA_ListItem_C", "BndEvt__UIW_QA_ListItem_Btn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_QA_ListItem.UIW_QA_ListItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_QA_ListItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_QA_ListItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
