#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Shop

#include "Basic.hpp"

#include "UIW_Shop_classes.hpp"
#include "UIW_Shop_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_Shop.UIW_Shop_C.ExecuteUbergraph_UIW_Shop
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::ExecuteUbergraph_UIW_Shop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "ExecuteUbergraph_UIW_Shop");

	Params::UIW_Shop_C_ExecuteUbergraph_UIW_Shop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BndEvt__UIW_Shop_List_Item_Locker_K2Node_ComponentBoundEvent_4_OnListItemSelectionChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Shop_C::BndEvt__UIW_Shop_List_Item_Locker_K2Node_ComponentBoundEvent_4_OnListItemSelectionChangedDynamic__DelegateSignature(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BndEvt__UIW_Shop_List_Item_Locker_K2Node_ComponentBoundEvent_4_OnListItemSelectionChangedDynamic__DelegateSignature");

	Params::UIW_Shop_C_BndEvt__UIW_Shop_List_Item_Locker_K2Node_ComponentBoundEvent_4_OnListItemSelectionChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BndEvt__UIW_Shop_List_Item_Inven_K2Node_ComponentBoundEvent_3_OnListItemSelectionChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Shop_C::BndEvt__UIW_Shop_List_Item_Inven_K2Node_ComponentBoundEvent_3_OnListItemSelectionChangedDynamic__DelegateSignature(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BndEvt__UIW_Shop_List_Item_Inven_K2Node_ComponentBoundEvent_3_OnListItemSelectionChangedDynamic__DelegateSignature");

	Params::UIW_Shop_C_BndEvt__UIW_Shop_List_Item_Inven_K2Node_ComponentBoundEvent_3_OnListItemSelectionChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BndEvt__UIW_Shop_Btn_Select_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::BndEvt__UIW_Shop_Btn_Select_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BndEvt__UIW_Shop_Btn_Select_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature");

	Params::UIW_Shop_C_BndEvt__UIW_Shop_Btn_Select_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BndEvt__UIW_Shop_Btn_Back_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::BndEvt__UIW_Shop_Btn_Back_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BndEvt__UIW_Shop_Btn_Back_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature");

	Params::UIW_Shop_C_BndEvt__UIW_Shop_Btn_Back_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_Shop_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.OnReady
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Shop_C::OnReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.MoveLeftTab
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::MoveLeftTab(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "MoveLeftTab");

	Params::UIW_Shop_C_MoveLeftTab Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.MoveRightTab
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::MoveRightTab(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "MoveRightTab");

	Params::UIW_Shop_C_MoveRightTab Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.RefreshTab
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Shop_C::RefreshTab()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "RefreshTab");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.ChangeTab
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Shop_C::ChangeTab(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "ChangeTab");

	Params::UIW_Shop_C_ChangeTab Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.FocusManage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Shop_C::FocusManage(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "FocusManage");

	Params::UIW_Shop_C_FocusManage Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.SetSelectedItem
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Shop_C::SetSelectedItem(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "SetSelectedItem");

	Params::UIW_Shop_C_SetSelectedItem Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.DoubleClickListItem
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::DoubleClickListItem(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "DoubleClickListItem");

	Params::UIW_Shop_C_DoubleClickListItem Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.CallbackBuy
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     Popup                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::CallbackBuy(class UUIW_Popup_C* Popup, class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "CallbackBuy");

	Params::UIW_Shop_C_CallbackBuy Parms{};

	Parms.Popup = Popup;
	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.CallbackSell
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     Popup                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::CallbackSell(class UUIW_Popup_C* Popup, class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "CallbackSell");

	Params::UIW_Shop_C_CallbackSell Parms{};

	Parms.Popup = Popup;
	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnBuySpinnerUp
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnBuySpinnerUp(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnBuySpinnerUp");

	Params::UIW_Shop_C_OnBuySpinnerUp Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnBuySpinnerDown
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnBuySpinnerDown(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnBuySpinnerDown");

	Params::UIW_Shop_C_OnBuySpinnerDown Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnSellSpinnerUp
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnSellSpinnerUp(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnSellSpinnerUp");

	Params::UIW_Shop_C_OnSellSpinnerUp Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnSellSpinnerDown
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnSellSpinnerDown(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnSellSpinnerDown");

	Params::UIW_Shop_C_OnSellSpinnerDown Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.CallbackContextMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::CallbackContextMenu(class FName EventName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "CallbackContextMenu");

	Params::UIW_Shop_C_CallbackContextMenu Parms{};

	Parms.EventName = EventName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnActive
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Shop_C::OnActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.OnSellRepeatDecrease
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnSellRepeatDecrease(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnSellRepeatDecrease");

	Params::UIW_Shop_C_OnSellRepeatDecrease Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnSellRepeatIncrease
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnSellRepeatIncrease(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnSellRepeatIncrease");

	Params::UIW_Shop_C_OnSellRepeatIncrease Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnBuyRepeatDecrease
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnBuyRepeatDecrease(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnBuyRepeatDecrease");

	Params::UIW_Shop_C_OnBuyRepeatDecrease Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.OnBuyRepeatIncrease
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::OnBuyRepeatIncrease(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnBuyRepeatIncrease");

	Params::UIW_Shop_C_OnBuyRepeatIncrease Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BindRepeatOnPopupBuy
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     CurrentPopup_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::BindRepeatOnPopupBuy(class UUIW_Popup_C* CurrentPopup_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BindRepeatOnPopupBuy");

	Params::UIW_Shop_C_BindRepeatOnPopupBuy Parms{};

	Parms.CurrentPopup_0 = CurrentPopup_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.BindRepeatOnPopupSell
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     CurrentPopup_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::BindRepeatOnPopupSell(class UUIW_Popup_C* CurrentPopup_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "BindRepeatOnPopupSell");

	Params::UIW_Shop_C_BindRepeatOnPopupSell Parms{};

	Parms.CurrentPopup_0 = CurrentPopup_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.HideFocusOnScroll
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CurerntOffset                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::HideFocusOnScroll(float CurerntOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "HideFocusOnScroll");

	Params::UIW_Shop_C_HideFocusOnScroll Parms{};

	Parms.CurerntOffset = CurerntOffset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.SetSelectedList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULTileView*                       ListView                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::SetSelectedList(class ULTileView* ListView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "SetSelectedList");

	Params::UIW_Shop_C_SetSelectedList Parms{};

	Parms.ListView = ListView;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Shop.UIW_Shop_C.HideAllList
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_Shop_C::HideAllList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "HideAllList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.SetListItem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UListView*                        ListView                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UObject*>&                 ListData                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32*                                  PrevSelectedIndex                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::SetListItem(class UListView* ListView, TArray<class UObject*>& ListData, int32* PrevSelectedIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "SetListItem");

	Params::UIW_Shop_C_SetListItem Parms{};

	Parms.ListView = ListView;
	Parms.ListData = std::move(ListData);

	UObject::ProcessEvent(Func, &Parms);

	ListData = std::move(Parms.ListData);

	if (PrevSelectedIndex != nullptr)
		*PrevSelectedIndex = Parms.PrevSelectedIndex;
}


// Function UIW_Shop.UIW_Shop_C.AddListEmptyFill
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UObject*>&                 DataArr                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   ColumnCnt                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           DataClass                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::AddListEmptyFill(TArray<class UObject*>& DataArr, int32 ColumnCnt, class UClass* DataClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "AddListEmptyFill");

	Params::UIW_Shop_C_AddListEmptyFill Parms{};

	Parms.DataArr = std::move(DataArr);
	Parms.ColumnCnt = ColumnCnt;
	Parms.DataClass = DataClass;

	UObject::ProcessEvent(Func, &Parms);

	DataArr = std::move(Parms.DataArr);
}


// Function UIW_Shop.UIW_Shop_C.NavToTop
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Shop_C::NavToTop(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "NavToTop");

	Params::UIW_Shop_C_NavToTop Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.NavToSmall1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Shop_C::NavToSmall1(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "NavToSmall1");

	Params::UIW_Shop_C_NavToSmall1 Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.NavToSmall2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Shop_C::NavToSmall2(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "NavToSmall2");

	Params::UIW_Shop_C_NavToSmall2 Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.NavToBottom
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Shop_C::NavToBottom(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "NavToBottom");

	Params::UIW_Shop_C_NavToBottom Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.GetBuyCountWithLimit
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ULProduct*                        Product                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsOverBuyLimit                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

int32 UUIW_Shop_C::GetBuyCountWithLimit(class ULProduct* Product, bool* IsOverBuyLimit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "GetBuyCountWithLimit");

	Params::UIW_Shop_C_GetBuyCountWithLimit Parms{};

	Parms.Product = Product;

	UObject::ProcessEvent(Func, &Parms);

	if (IsOverBuyLimit != nullptr)
		*IsOverBuyLimit = Parms.IsOverBuyLimit;

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.GetBuyCountTotal
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ULProduct*                        Product                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UUIW_Shop_C::GetBuyCountTotal(class ULProduct* Product)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "GetBuyCountTotal");

	Params::UIW_Shop_C_GetBuyCountTotal Parms{};

	Parms.Product = Product;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.ListPendingCheck
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_Shop_C::ListPendingCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "ListPendingCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Shop.UIW_Shop_C.GetBottomList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTileView**                       AsTile_View                                            (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Shop_C::GetBottomList(class UTileView** AsTile_View)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "GetBottomList");

	Params::UIW_Shop_C_GetBottomList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsTile_View != nullptr)
		*AsTile_View = Parms.AsTile_View;
}


// Function UIW_Shop.UIW_Shop_C.NavToLRLoop
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Shop_C::NavToLRLoop(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "NavToLRLoop");

	Params::UIW_Shop_C_NavToLRLoop Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Shop.UIW_Shop_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Shop_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Shop_C", "OnMouseButtonUp");

	Params::UIW_Shop_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
