#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Spinner_Number

#include "Basic.hpp"

#include "UIW_Spinner_Number_classes.hpp"
#include "UIW_Spinner_Number_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_Spinner_Number.UIW_Spinner_Number_C.SetNumber
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Number                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Spinner_Number_C::SetNumber(int32 Number)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Spinner_Number_C", "SetNumber");

	Params::UIW_Spinner_Number_C_SetNumber Parms{};

	Parms.Number = Number;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Spinner_Number.UIW_Spinner_Number_C.SetColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEdited                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Spinner_Number_C::SetColor(bool IsEdited)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Spinner_Number_C", "SetColor");

	Params::UIW_Spinner_Number_C_SetColor Parms{};

	Parms.IsEdited = IsEdited;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
