#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_BG_Title

#include "Basic.hpp"

#include "ProjectP_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UIW_BG_Title.UIW_BG_Title_C.ExecuteUbergraph_UIW_BG_Title
// 0x001C (0x001C - 0x0000)
struct UIW_BG_Title_C_ExecuteUbergraph_UIW_BG_Title final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTweenEase                             K2Node_MakeStruct_TweenEase;                       // 0x0004(0x000C)(NoDestructor)
	struct FTweenEase                             K2Node_MakeStruct_TweenEase_1;                     // 0x0010(0x000C)(NoDestructor)
};
DUMPER7_ASSERTS_UIW_BG_Title_C_ExecuteUbergraph_UIW_BG_Title;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
