#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_CharacterUpgrade

#include "Basic.hpp"

#include "UIW_CharacterUpgrade_classes.hpp"
#include "UIW_CharacterUpgrade_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.ExecuteUbergraph_UIW_CharacterUpgrade
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::ExecuteUbergraph_UIW_CharacterUpgrade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "ExecuteUbergraph_UIW_CharacterUpgrade");

	Params::UIW_CharacterUpgrade_C_ExecuteUbergraph_UIW_CharacterUpgrade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__UIW_CharacterUpgrade_Btn_Increase_K2Node_ComponentBoundEvent_4_OnRepeat__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__UIW_CharacterUpgrade_Btn_Increase_K2Node_ComponentBoundEvent_4_OnRepeat__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__UIW_CharacterUpgrade_Btn_Increase_K2Node_ComponentBoundEvent_4_OnRepeat__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__UIW_CharacterUpgrade_Btn_Increase_K2Node_ComponentBoundEvent_4_OnRepeat__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__UIW_CharacterUpgrade_Btn_Decrease_K2Node_ComponentBoundEvent_0_OnRepeat__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__UIW_CharacterUpgrade_Btn_Decrease_K2Node_ComponentBoundEvent_0_OnRepeat__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__UIW_CharacterUpgrade_Btn_Decrease_K2Node_ComponentBoundEvent_0_OnRepeat__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__UIW_CharacterUpgrade_Btn_Decrease_K2Node_ComponentBoundEvent_0_OnRepeat__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.OnOpenTweenComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             CategoryName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::OnOpenTweenComplete(class FName CategoryName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "OnOpenTweenComplete");

	Params::UIW_CharacterUpgrade_C_OnOpenTweenComplete Parms{};

	Parms.CategoryName = CategoryName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__Btn_Increase_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__Btn_Increase_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__Btn_Increase_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__Btn_Increase_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__Btn_Decrease_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__Btn_Decrease_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__Btn_Decrease_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__Btn_Decrease_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__Btn_Select_K2Node_ComponentBoundEvent_8_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__Btn_Select_K2Node_ComponentBoundEvent_8_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__Btn_Select_K2Node_ComponentBoundEvent_8_OnActive__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__Btn_Select_K2Node_ComponentBoundEvent_8_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.BndEvt__Btn_Back_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::BndEvt__Btn_Back_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "BndEvt__Btn_Back_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature");

	Params::UIW_CharacterUpgrade_C_BndEvt__Btn_Back_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_CharacterUpgrade_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.RefreshRequireErgo
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::RefreshRequireErgo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "RefreshRequireErgo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.RefreshBaseStat
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::RefreshBaseStat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "RefreshBaseStat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.RefreshStatGroup
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::RefreshStatGroup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "RefreshStatGroup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.FocusManage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_CharacterUpgrade_C::FocusManage(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "FocusManage");

	Params::UIW_CharacterUpgrade_C_FocusManage Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetFocusedBaseStat
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_CharacterUpgrade_Stat_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::SetFocusedBaseStat(class UUIW_CharacterUpgrade_Stat_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetFocusedBaseStat");

	Params::UIW_CharacterUpgrade_C_SetFocusedBaseStat Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetSelectedBaseStat
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_CharacterUpgrade_Stat_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::SetSelectedBaseStat(class UUIW_CharacterUpgrade_Stat_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetSelectedBaseStat");

	Params::UIW_CharacterUpgrade_C_SetSelectedBaseStat Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetSelectedSpinner
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::SetSelectedSpinner(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetSelectedSpinner");

	Params::UIW_CharacterUpgrade_C_SetSelectedSpinner Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.ReleaseUpSpinner
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::ReleaseUpSpinner(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "ReleaseUpSpinner");

	Params::UIW_CharacterUpgrade_C_ReleaseUpSpinner Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.ReleaseDownSpinner
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::ReleaseDownSpinner(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "ReleaseDownSpinner");

	Params::UIW_CharacterUpgrade_C_ReleaseDownSpinner Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CallbackCancelAbillity
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     Popup                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::CallbackCancelAbillity(class UUIW_Popup_C* Popup, class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CallbackCancelAbillity");

	Params::UIW_CharacterUpgrade_C_CallbackCancelAbillity Parms{};

	Parms.Popup = Popup;
	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CheckEdited
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::CheckEdited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CheckEdited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.RefreshStatDiff
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   RemainSoul                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct FLSecondStatDiffData>&CommonDiff                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FLSecondStatDiffData>&    Weapon1stDiff                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FLSecondStatDiffData>&    Weapon2stDiff                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUIW_CharacterUpgrade_C::RefreshStatDiff(int32 RemainSoul, const TArray<struct FLSecondStatDiffData>& CommonDiff, TArray<struct FLSecondStatDiffData>& Weapon1stDiff, TArray<struct FLSecondStatDiffData>& Weapon2stDiff)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "RefreshStatDiff");

	Params::UIW_CharacterUpgrade_C_RefreshStatDiff Parms{};

	Parms.RemainSoul = RemainSoul;
	Parms.CommonDiff = std::move(CommonDiff);
	Parms.Weapon1stDiff = std::move(Weapon1stDiff);
	Parms.Weapon2stDiff = std::move(Weapon2stDiff);

	UObject::ProcessEvent(Func, &Parms);

	Weapon1stDiff = std::move(Parms.Weapon1stDiff);
	Weapon2stDiff = std::move(Parms.Weapon2stDiff);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.RequestCloseWindow
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::RequestCloseWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "RequestCloseWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.AddEventBinding
// (Protected, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::AddEventBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "AddEventBinding");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.OnReady
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::OnReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "OnReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.ChangeFirstStat
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::ChangeFirstStat(class UUIW_Spinner_C* Spinner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "ChangeFirstStat");

	Params::UIW_CharacterUpgrade_C_ChangeFirstStat Parms{};

	Parms.Spinner = Spinner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetEnabledWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_CharacterUpgrade_C::SetEnabledWindow(bool IsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetEnabledWindow");

	Params::UIW_CharacterUpgrade_C_SetEnabledWindow Parms{};

	Parms.IsEnabled = IsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.Temp_InitFocus
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::Temp_InitFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "Temp_InitFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetEnabledButton
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsCanLevelUpAndNext                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsCanLevelDown                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_CharacterUpgrade_C::SetEnabledButton(bool IsCanLevelUpAndNext, bool IsCanLevelDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetEnabledButton");

	Params::UIW_CharacterUpgrade_C_SetEnabledButton Parms{};

	Parms.IsCanLevelUpAndNext = IsCanLevelUpAndNext;
	Parms.IsCanLevelDown = IsCanLevelDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.OnActivePopup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Popup_C*                     Popup                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_CharacterUpgrade_C::OnActivePopup(class UUIW_Popup_C* Popup, class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "OnActivePopup");

	Params::UIW_CharacterUpgrade_C_OnActivePopup Parms{};

	Parms.Popup = Popup;
	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.OnUpgrade
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::OnUpgrade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "OnUpgrade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.OnFocusedUpgrade
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::OnFocusedUpgrade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "OnFocusedUpgrade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.NavToUpgradeBtn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_CharacterUpgrade_C::NavToUpgradeBtn(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "NavToUpgradeBtn");

	Params::UIW_CharacterUpgrade_C_NavToUpgradeBtn Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CheckCanLevelUp
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanLevelUp_0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_CharacterUpgrade_C::CheckCanLevelUp(class UUIW_Spinner_C* Spinner, int32 Direction, bool* CanLevelUp_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CheckCanLevelUp");

	Params::UIW_CharacterUpgrade_C_CheckCanLevelUp Parms{};

	Parms.Spinner = Spinner;
	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);

	if (CanLevelUp_0 != nullptr)
		*CanLevelUp_0 = Parms.CanLevelUp_0;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.GetLevelUpCount
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const class UUIW_Spinner_C*&            Spinner                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ELFirstStat*                            Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UUIW_CharacterUpgrade_C::GetLevelUpCount(const class UUIW_Spinner_C*& Spinner, int32 Direction, ELFirstStat* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "GetLevelUpCount");

	Params::UIW_CharacterUpgrade_C_GetLevelUpCount Parms{};

	Parms.Spinner = Spinner;
	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;

	return Parms.ReturnValue;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CanLevelDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UUIW_Spinner_C*                   Spinner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LevelUpCount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CanLevelUp_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool*                                   CanDownLevel                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_CharacterUpgrade_C::CanLevelDown(class UUIW_Spinner_C* Spinner, int32 Direction, int32 LevelUpCount, bool CanLevelUp_0, bool* CanDownLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CanLevelDown");

	Params::UIW_CharacterUpgrade_C_CanLevelDown Parms{};

	Parms.Spinner = Spinner;
	Parms.Direction = Direction;
	Parms.LevelUpCount = LevelUpCount;
	Parms.CanLevelUp_0 = CanLevelUp_0;

	UObject::ProcessEvent(Func, &Parms);

	if (CanDownLevel != nullptr)
		*CanDownLevel = Parms.CanDownLevel;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.SetupInitValue
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::SetupInitValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "SetupInitValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CanLevelUp
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Output_Get                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_CharacterUpgrade_C::CanLevelUp(bool* Output_Get)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CanLevelUp");

	Params::UIW_CharacterUpgrade_C_CanLevelUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output_Get != nullptr)
		*Output_Get = Parms.Output_Get;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.CanChangeFirstStat
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ELFirstStat                             FirstStat                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ChangeData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  OutErrorCode                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UUIW_CharacterUpgrade_C::CanChangeFirstStat(ELFirstStat FirstStat, int32 ChangeData, int32* OutErrorCode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "CanChangeFirstStat");

	Params::UIW_CharacterUpgrade_C_CanChangeFirstStat Parms{};

	Parms.FirstStat = FirstStat;
	Parms.ChangeData = ChangeData;

	UObject::ProcessEvent(Func, &Parms);

	if (OutErrorCode != nullptr)
		*OutErrorCode = Parms.OutErrorCode;

	return Parms.ReturnValue;
}


// Function UIW_CharacterUpgrade.UIW_CharacterUpgrade_C.ClearEventBinding
// (Protected, BlueprintCallable, BlueprintEvent)

void UUIW_CharacterUpgrade_C::ClearEventBinding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_CharacterUpgrade_C", "ClearEventBinding");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
