#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Page_Indicator

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UIW_Page_Indicator.UIW_Page_Indicator_C
// 0x0008 (0x0268 - 0x0260)
class UUIW_Page_Indicator_C final : public UUserWidget
{
public:
	class UHorizontalBox*                         Group_Page;                                        // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetData(int32 Current, int32 Max);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIW_Page_Indicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIW_Page_Indicator_C")
	}
	static class UUIW_Page_Indicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIW_Page_Indicator_C>();
	}
};
DUMPER7_ASSERTS_UUIW_Page_Indicator_C;

SDK_NAMESPACE_END
