#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Alert_Recovery

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UIW_Alert_Recovery.UIW_Alert_Recovery_C
// 0x0018 (0x0278 - 0x0260)
class UUIW_Alert_Recovery_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Ani_Start;                                         // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Img_Text_Base;                                     // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UIW_Alert_Recovery(int32 EntryPoint);
	void Destruct();
	void Construct();
	void Hide();
	void Show(float Delay);
	void Finished_36209D0B4A6B89BD35A996BDDC605A72();
	void SetAlertRecovery();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIW_Alert_Recovery_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIW_Alert_Recovery_C")
	}
	static class UUIW_Alert_Recovery_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIW_Alert_Recovery_C>();
	}
};
DUMPER7_ASSERTS_UUIW_Alert_Recovery_C;

SDK_NAMESPACE_END
