#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Slot_Large

#include "Basic.hpp"

#include "UIW_Slot_Large_classes.hpp"
#include "UIW_Slot_Large_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_Slot_Large.UIW_Slot_Large_C.ExecuteUbergraph_UIW_Slot_Large
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Slot_Large_C::ExecuteUbergraph_UIW_Slot_Large(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "ExecuteUbergraph_UIW_Slot_Large");

	Params::UIW_Slot_Large_C_ExecuteUbergraph_UIW_Slot_Large Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_Slot_Large_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UUIW_Slot_Large_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "OnFocusLost");

	Params::UIW_Slot_Large_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.OnMouseButtonDoubleClick
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 InMyGeometry                                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             InMouseEvent                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Slot_Large_C::OnMouseButtonDoubleClick(const struct FGeometry& InMyGeometry, const struct FPointerEvent& InMouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "OnMouseButtonDoubleClick");

	Params::UIW_Slot_Large_C_OnMouseButtonDoubleClick Parms{};

	Parms.InMyGeometry = std::move(InMyGeometry);
	Parms.InMouseEvent = std::move(InMouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.Set Item
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          ListItem                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Slot_Large_C::Set_Item(class UObject* ListItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "Set Item");

	Params::UIW_Slot_Large_C_Set_Item Parms{};

	Parms.ListItem = ListItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Slot_Large_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "OnFocusReceived");

	Params::UIW_Slot_Large_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Slot_Large_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "OnMouseButtonDown");

	Params::UIW_Slot_Large_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.SetMoveFocusEffect
// (Protected, BlueprintCallable, BlueprintEvent)

void UUIW_Slot_Large_C::SetMoveFocusEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "SetMoveFocusEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Slot_Large.UIW_Slot_Large_C.SetEquiped
// (Protected, BlueprintCallable, BlueprintEvent)

void UUIW_Slot_Large_C::SetEquiped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Slot_Large_C", "SetEquiped");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
