#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_HUD_FatalAttack

#include "Basic.hpp"

#include "UIW_HUD_FatalAttack_classes.hpp"
#include "UIW_HUD_FatalAttack_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_HUD_FatalAttack.UIW_HUD_FatalAttack_C.ExecuteUbergraph_UIW_HUD_FatalAttack
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_HUD_FatalAttack_C::ExecuteUbergraph_UIW_HUD_FatalAttack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_HUD_FatalAttack_C", "ExecuteUbergraph_UIW_HUD_FatalAttack");

	Params::UIW_HUD_FatalAttack_C_ExecuteUbergraph_UIW_HUD_FatalAttack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_HUD_FatalAttack.UIW_HUD_FatalAttack_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_HUD_FatalAttack_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_HUD_FatalAttack_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_HUD_FatalAttack.UIW_HUD_FatalAttack_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_HUD_FatalAttack_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_HUD_FatalAttack_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_HUD_FatalAttack.UIW_HUD_FatalAttack_C.AddIndicator
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_HUD_FatalAttack_C::AddIndicator(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_HUD_FatalAttack_C", "AddIndicator");

	Params::UIW_HUD_FatalAttack_C_AddIndicator Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_HUD_FatalAttack.UIW_HUD_FatalAttack_C.RemoveIndicator
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_HUD_FatalAttack_C::RemoveIndicator(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_HUD_FatalAttack_C", "RemoveIndicator");

	Params::UIW_HUD_FatalAttack_C_RemoveIndicator Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
