#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Record

#include "Basic.hpp"

#include "UIW_Record_classes.hpp"
#include "UIW_Record_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_Record.UIW_Record_C.ExecuteUbergraph_UIW_Record
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::ExecuteUbergraph_UIW_Record(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "ExecuteUbergraph_UIW_Record");

	Params::UIW_Record_C_ExecuteUbergraph_UIW_Record Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_Record_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.BndEvt__UIW_Record_Btn_Stop_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::BndEvt__UIW_Record_Btn_Stop_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "BndEvt__UIW_Record_Btn_Stop_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature");

	Params::UIW_Record_C_BndEvt__UIW_Record_Btn_Stop_K2Node_ComponentBoundEvent_3_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "Tick");

	Params::UIW_Record_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_Record_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.BndEvt__Btn_Close_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::BndEvt__Btn_Close_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "BndEvt__Btn_Close_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature");

	Params::UIW_Record_C_BndEvt__Btn_Close_K2Node_ComponentBoundEvent_2_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.BndEvt__Btn_Detail_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::BndEvt__Btn_Detail_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "BndEvt__Btn_Detail_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature");

	Params::UIW_Record_C_BndEvt__Btn_Detail_K2Node_ComponentBoundEvent_1_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.BndEvt__Btn_Play_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UUIW_Btn_Key_C*                   BtnKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::BndEvt__Btn_Play_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature(class UUIW_Btn_Key_C* BtnKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "BndEvt__Btn_Play_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature");

	Params::UIW_Record_C_BndEvt__Btn_Play_K2Node_ComponentBoundEvent_0_OnActive__DelegateSignature Parms{};

	Parms.BtnKey = BtnKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.RefreshList
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::RefreshList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "RefreshList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.OnSelectionChanged
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Record_C::OnSelectionChanged(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnSelectionChanged");

	Params::UIW_Record_C_OnSelectionChanged Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.OnDoubleClicked
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::OnDoubleClicked(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnDoubleClicked");

	Params::UIW_Record_C_OnDoubleClicked Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.FocusManage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_Record_C::FocusManage(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "FocusManage");

	Params::UIW_Record_C_FocusManage Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Record.UIW_Record_C.OnReady
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::OnReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.StartTween
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::StartTween()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "StartTween");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.OnPlay
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlaying                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             CodeName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::OnPlay(bool IsPlaying, class FName CodeName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnPlay");

	Params::UIW_Record_C_OnPlay Parms{};

	Parms.IsPlaying = IsPlaying;
	Parms.CodeName = CodeName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.OnPlayTime
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class USoundWave*                 PlayingSoundWave                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const float                             PlaybackPercent                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::OnPlayTime(const class USoundWave* PlayingSoundWave, const float PlaybackPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnPlayTime");

	Params::UIW_Record_C_OnPlayTime Parms{};

	Parms.PlayingSoundWave = PlayingSoundWave;
	Parms.PlaybackPercent = PlaybackPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.CheckButton
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::CheckButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "CheckButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.PlayReal
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::PlayReal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "PlayReal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.NavToTop
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Record_C::NavToTop(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "NavToTop");

	Params::UIW_Record_C_NavToTop Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Record.UIW_Record_C.NavToBottom
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIW_Record_C::NavToBottom(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "NavToBottom");

	Params::UIW_Record_C_NavToBottom Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_Record.UIW_Record_C.SetPlayRecord
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             CodeName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    NeedTweenAndNextPending                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_Record_C::SetPlayRecord(int32 Index_0, class FName CodeName, bool NeedTweenAndNextPending)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "SetPlayRecord");

	Params::UIW_Record_C_SetPlayRecord Parms{};

	Parms.Index_0 = Index_0;
	Parms.CodeName = CodeName;
	Parms.NeedTweenAndNextPending = NeedTweenAndNextPending;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_Record.UIW_Record_C.ListPendingCheck
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_Record_C::ListPendingCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "ListPendingCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_Record.UIW_Record_C.OnCompleteTweenEvent
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_Record_C::OnCompleteTweenEvent(class FName Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_Record_C", "OnCompleteTweenEvent");

	Params::UIW_Record_C_OnCompleteTweenEvent Parms{};

	Parms.Name_0 = Name_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
