#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_Module_TitleText

#include "Basic.hpp"

#include "UIW_Popup_Module_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UIW_Module_TitleText.UIW_Module_TitleText_C
// 0x0008 (0x02B0 - 0x02A8)
class UUIW_Module_TitleText_C final : public UUIW_Popup_Module_C
{
public:
	class URichTextBlock*                         Text_Title;                                        // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetModule(class UUIW_Popup_C* PopupWindow_0, const class FString& Data);
	void SetGameString(const class FString& String);
	void SetText(const class FText& Text);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIW_Module_TitleText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIW_Module_TitleText_C")
	}
	static class UUIW_Module_TitleText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIW_Module_TitleText_C>();
	}
};
DUMPER7_ASSERTS_UUIW_Module_TitleText_C;

SDK_NAMESPACE_END
