#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_ContextMenu

#include "Basic.hpp"

#include "UIW_ContextMenu_classes.hpp"
#include "UIW_ContextMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function UIW_ContextMenu.UIW_ContextMenu_C.ExecuteUbergraph_UIW_ContextMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_ContextMenu_C::ExecuteUbergraph_UIW_ContextMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "ExecuteUbergraph_UIW_ContextMenu");

	Params::UIW_ContextMenu_C_ExecuteUbergraph_UIW_ContextMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_ContextMenu_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_ContextMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.BndEvt__Button_126_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UUIW_ContextMenu_C::BndEvt__Button_126_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "BndEvt__Button_126_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.Set Context Menu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIW_Window_C*                    Window_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TMap<class FName, class FText>&   MenuList                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FVector2D&                 position                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_ContextMenu_C::Set_Context_Menu(class UUIW_Window_C* Window_0, const TMap<class FName, class FText>& MenuList, const struct FVector2D& position)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "Set Context Menu");

	Params::UIW_ContextMenu_C_Set_Context_Menu Parms{};

	Parms.Window_0 = Window_0;
	Parms.MenuList = std::move(MenuList);
	Parms.position = std::move(position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.ReleasedButton
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventName_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_ContextMenu_C::ReleasedButton(class FName EventName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "ReleasedButton");

	Params::UIW_ContextMenu_C_ReleasedButton Parms{};

	Parms.EventName_0 = EventName_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_ContextMenu_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "OnKeyUp");

	Params::UIW_ContextMenu_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.SelectedButton
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EventName_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_ContextMenu_C::SelectedButton(class FName EventName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "SelectedButton");

	Params::UIW_ContextMenu_C_SelectedButton Parms{};

	Parms.EventName_0 = EventName_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.OnSelect
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_ContextMenu_C::OnSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "OnSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_ContextMenu_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "OnFocusReceived");

	Params::UIW_ContextMenu_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIW_ContextMenu_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "OnMouseButtonDown");

	Params::UIW_ContextMenu_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.FirstFocus
// (Private, BlueprintCallable, BlueprintEvent)

void UUIW_ContextMenu_C::FirstFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "FirstFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_ContextMenu.UIW_ContextMenu_C.Close
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_ContextMenu_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_ContextMenu_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
